#!/bin/bash

apt update -y
apt-get upgrade -y
apt update -y
apt install python3
python3-pip
python3-dev
python3-distutils
python3-venv
tesseract-ocr
libtesseract-dev
mysql-server
pip3 install --upgrade pip
pip3 install pytesseract
pip3 install tesseract
pip3 install pdf2image
pip3 install django -U
apt-get install -y git curl wget
